name: dps-email-worker - Build Image

on:
  push:
    branches:
      - main
    paths:
      - "src/dps-email-worker/**"
      - ".github/workflows/dev-dps-email-worker"
  workflow_dispatch:
    branches:
      - main

jobs:  
  
# This workflow is used to build & scan image using trivy vulnerability scanner and upload the results to github security tab
  build-scan-image:
    name: Build & Scan Image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up JDK build environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
        
      # Runs build steps
      - name: Maven Package
        run: mvn -ntp clean package
        
      - name: Maven Verify
        run: mvn -ntp clean verify

      #Build image for scanning
      - name: Build an image from Dockerfile
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t dev-email-worker:${{ github.sha }} .

      #Run Vulnerability Scan usinig Trivy scanner
      - name: Run Trivy vulnerability scanner for jag-icon2-common-application
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: "dev-email-worker:${{ github.sha }}"
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL
        
        #Upload results to the Github security tab.
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: trivy-results.sarif
          
